import { jsx } from "@b9g/crank/standalone";
import { renderer } from "@b9g/crank/html";
import { Router } from "@b9g/router";
import { trailingSlash } from "@b9g/router/middleware";

import { collectDocuments } from "./models/document.js";
import HomeView from "./views/home.js";
import GuideView from "./views/guide.js";
import NotFoundView from "./views/not-found.js";

const router = new Router();

// Redirect /path -> /path/ so URLs match the static directory layout.
router.use(trailingSlash("append"));

async function renderView(
  View: any,
  url: string,
  params: Record<string, string> = {},
): Promise<Response> {
  if (!url.endsWith("/")) {
    url = url + "/";
  }

  const html = await renderer.render(jsx`<${View} url=${url} params=${params} />`);
  return new Response(html, { headers: { "Content-Type": "text/html" } });
}

router.route("/").get(async (request) => {
  const url = new URL(request.url);
  return renderView(HomeView, url.pathname);
});

router.route("/docs/:slug/").get(async (request, context) => {
  const url = new URL(request.url);
  return renderView(GuideView, url.pathname, context.params);
});

// Serve pagefind search assets (generated by the static build).
router.route("/pagefind/:path*").get(async (request, context) => {
  try {
    const pagefindDir = await self.directories.open("pagefind");
    const parts = (context.params.path || "").split("/").filter(Boolean);
    let dir = pagefindDir;
    for (let i = 0; i < parts.length - 1; i++) {
      dir = await dir.getDirectoryHandle(parts[i]);
    }
    const fileName = parts[parts.length - 1] || "";
    const handle = await dir.getFileHandle(fileName);
    const file = await handle.getFile();
    const ext = fileName.slice(fileName.lastIndexOf(".")).toLowerCase();
    const contentType =
      ext === ".js"
        ? "application/javascript"
        : ext === ".css"
          ? "text/css"
          : "application/octet-stream";
    return new Response(await file.arrayBuffer(), {
      headers: { "Content-Type": contentType },
    });
  } catch {
    return new Response("Not Found (run the static build first)", { status: 404 });
  }
});

router.route("*").all(async (request) => {
  const url = new URL(request.url);
  const html = await renderer.render(
    jsx`<${NotFoundView} url=${url.pathname} params=${{}} />`,
  );
  return new Response(html, {
    status: 404,
    headers: { "Content-Type": "text/html" },
  });
});

self.addEventListener("fetch", (event: any) => {
  event.respondWith(router.handle(event.request));
});

self.addEventListener("install", (event: any) => {
  event.waitUntil(generateStaticSite());
});

async function writeFile(
  bucket: FileSystemDirectoryHandle,
  filePath: string,
  content: string | ArrayBuffer,
): Promise<void> {
  const parts = filePath.split("/");
  let dir = bucket;
  for (let i = 0; i < parts.length - 1; i++) {
    dir = await dir.getDirectoryHandle(parts[i], { create: true });
  }
  const handle = await dir.getFileHandle(parts[parts.length - 1], { create: true });
  const writable = await handle.createWritable();
  await writable.write(content as any);
  await writable.close();
}

async function generateStaticSite() {
  if (import.meta.env.MODE !== "production") {
    return;
  }

  const logger = self.loggers.get(["shovel", "server"]);
  const pub = await self.directories.open("public");

  const docsDir = await self.directories.open("docs");
  const guidesDir = await docsDir.getDirectoryHandle("guides");
  const guideDocs = await collectDocuments(guidesDir);

  const routes = ["/", ...guideDocs.map((doc) => doc.url)];
  logger.info(`Pre-rendering ${routes.length} routes...`);

  for (const route of routes) {
    const response = await fetch(route);
    if (!response.ok) {
      logger.error(`Failed to render ${route}: ${response.status}`);
      continue;
    }
    const content = await response.text();
    const filePath = route === "/" ? "index.html" : `${route.slice(1)}index.html`;
    await writeFile(pub, filePath, content);
    logger.info(`Generated ${route}`);
  }

  // 404 page (GitHub Pages serves /404.html for unknown paths).
  const notFound = await fetch("/__not_found__");
  await writeFile(pub, "404.html", await notFound.text());
  logger.info("Generated 404.html");

  logger.info("Static site generation complete!");
}
